server {

    # Nginxが受け付けるポート番号
    listen 80;

    # サーバー名（ローカル環境なので localhost）
    server_name localhost;

    # Web公開するフォルダ
    # Laravelでは public フォルダだけを公開する
    root /var/www/html/public;

    # デフォルトで表示するファイル
    index index.php index.html;

    # -----------------------------
    # URLへのアクセス設定
    # -----------------------------
    location / {

        # リクエストされたファイルが存在すれば表示
        # 存在しなければ index.php に渡す
        # Laravelのルーティングを動かすために必要
        try_files $uri $uri/ /index.php?$query_string;
    }

    # -----------------------------
    # PHPファイルの実行設定
    # -----------------------------
    location ~ \.php$ {

        # docker-compose.yml の php サービスへ処理を渡す
        fastcgi_pass php:9000;

        # 最初に実行するPHPファイル
        fastcgi_index index.php;

        # FastCGIの基本設定を読み込む
        include fastcgi_params;

        # 実行するPHPファイルの場所をPHPへ伝える
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # -----------------------------
    # .htaccessなどの隠しファイルは
    # ブラウザからアクセス禁止
    # -----------------------------
    location ~ /\.ht {
        deny all;
    }
}